### ISSUE TITLE
WiiFlow WFL

### ISSUE THREAD

**Issue by vonmillhausen** [OpenShopChannel/outdated-apps#101]
### Currently Listed Version

5.5.4

### URL to new version

https://github.com/Fledge68/WiiFlow_Lite/releases/tag/v.5.5.4_1

### Version of Updated App

5.5.4-1

### Select listing type

Apps

### More Information

* fix for 'auto' game IOS option. in v5.5.4 'auto' causes the game to use a d2x cios base 38 if you have it installed, which prevents game from booting. this fix prevents this from happening

**Comment by larsenv** [comment]
Could you please go through the outdated apps and make sure they're taken care of. There's a couple of issues here that I believe have gone unprocessed, and maybe adjusting your settings to receive notifications about outdated apps could be useful. FYI, the latest version is 5.5.4-1, not 5.5.5-1

**Comment by vonmillhausen** [comment]
Oops, typo! Corrected the `5.5.5_1` to `5.5.4-1` 👍

**Comment by Artuto** [comment]
This app was updated automatically days ago.
