### ISSUE TITLE
Cookwii Clicker

### ISSUE THREAD

**Issue by TheHighTide** [OpenShopChannel/outdated-apps#102]
### Currently Listed Version

0.0.2

### URL to new version

https://hightide.coolpage.biz/projects/cookwii_clicker/source.zip

### Version of Updated App

0.2.0

### Select listing type

Apps

### More Information

No.

**Comment by GabubuAvailable** [comment]
According to your link, the latest version is 0.1.0. And according to https://github.com/OpenShopChannel/Apps/blob/master/contents/CookwiiClicker.oscmeta the link is the same as you sent.

**Comment by TheHighTide** [comment]
But why do I see this when I go to the catalog?
![Screenshot_20240630-134004](https://github.com/OpenShopChannel/outdated-apps/assets/84487860/605d3b87-397b-4634-893b-f9a33a8cd316)

**Comment by GabubuAvailable** [comment]
Looks like me and @playerjmr found a problem. We'll check it and come back with an answer.

**Comment by GabubuAvailable** [comment]
According to your `app version` from the meta.xml file, it is recommended to go with `<app version="1">` instead of `<app version="2">`. Can you try to change that please?

**Comment by GabubuAvailable** [comment]
Once you do that, the indexer will do a re-check again and I can approve your version afterwards.

**Comment by TheHighTide** [comment]
I've changed it

**Comment by Artuto** [comment]
When did you push the update?

**Comment by TheHighTide** [comment]
The update was about 2 hours ago but I was told not to push it to this GitHub cause they set my game to autoupdate

**Comment by Artuto** [comment]
RepoMan indexes every 6 hours, you pushed after it finished updating. There is not a bug, just wait and it will be updated after review.
