### ISSUE TITLE
Kidspaint

### ISSUE THREAD

**Issue by ghost** [OpenShopChannel/outdated-apps#104]
### Currently Listed Version

2.0.2

### URL to new version

<removed, copyrighted content>

### Version of Updated App

???

### Select listing type

Apps

### More Information

The homebrew version no longer works because there is now a WiiWare version called "Paint Splash". The home-brew version always gives you "More Things. More Fun. Snd way better! on WiiWare!"

**Comment by GabubuAvailable** [comment]
Sorry but this is not accepted, considering that what you sent as the "URL to new version" is a WAD downloaded from online. Open Shop Channel is not a piracy service but a homebrew library service with open source apps made by the community.

**Comment by ghost** [comment]
Sorry for sending the wad download, but the homebrew version doesn't work.
I know what Open Shop Channel is

**Comment by ghost** [comment]
The home-brew version doesn't work anyway

**Comment by Artuto** [comment]
How does it not work?

**Comment by ghost** [comment]
When you launch the HomeBrew version, it says "More Fun! More Features! and
way better! on WiiWare.
