### ISSUE TITLE
WiiFlow WFL

### ISSUE THREAD

**Issue by TechnoEggnog-2763** [OpenShopChannel/outdated-apps#105]
### Currently Listed Version

5.5.4

### URL to new version

https://github.com/Fledge68/WiiFlow_Lite/releases/tag/v.5.5.4_1

### Version of Updated App

v5.5.4-1

### Select listing type

Apps

### More Information

fix for 'auto' game IOS option. in v5.5.4 'auto' causes the game to use a d2x cios base 38 if you have it installed, which prevents game from booting. this fix prevents this from happening

**Comment by playerjmr** [comment]
I checked the download. The latest version is already being used, fledge had just not been bothered to update the meta.xml.

**Comment by GabubuAvailable** [comment]
It's the same version. I've compared the meta.xml files from both sources and these are the same. The issue is that fledge forgot to update the meta.xml file, but the app is indeed up to date!
