### ISSUE TITLE
BounceWii

### ISSUE THREAD

**Issue by Greeg0** [OpenShopChannel/outdated-apps#106]
### Currently Listed Version

v0.2.1

### URL to new version

https://github.com/Greeg0/BounceWii/releases/tag/v1.0.0

### Version of Updated App

v1.0.0

### Select listing type

Apps

### More Information

No.

**Comment by GabubuAvailable** [comment]
Sorry, it was on waitlist. I've approved your new version now and it would be indexed automatically! 🙂
