### ISSUE TITLE
Dump Mii NAND

### ISSUE THREAD

**Issue by LoannMKW** [OpenShopChannel/outdated-apps#107]
### Currently Listed Version

v1.2

### URL to new version

https://oscwii.org/library/app/DmpMiNND

### Version of Updated App

v1.2

### Select listing type

Apps

### More Information

Hi, i'm sending that message to say that Dump Mii is very dangerous for the Wii console, per example, there is a VERY BIG CHANCE that it can corrupt the SD Card, and the SD Card become unusable and it cant be formated a new time (It happened to 2 of my friends). So please remove it from the open shop channel please and say to the users to use Bootmii to backup their Wii nand 🙏🏻

**Comment by LoannMKW** [comment]
![image](https://github.com/OpenShopChannel/outdated-apps/assets/151388753/e52ec56d-f680-459a-8fed-27819e9bdaee)

**Comment by GabubuAvailable** [comment]
Where did you get the SD card from? The corruption cannot be made by that app tho, so I think your SD card have a fake capacity.

**Comment by GabubuAvailable** [comment]
Can I have a picture of your SD card please?

**Comment by Naim2000** [comment]
Probably really shitty SD card. That looks like corruption caused from the SD throwing a fit

**Comment by LoannMKW** [comment]
Ill see that with my friend, bc i sent this post for him :)

**Comment by ghost** [comment]
Wait I also got this when using the app!
And my sd card is a 2GB sandisk so it must be something with the app

**Comment by LoannMKW** [comment]
Thanks marioexpert, thought it was just my friends, but im not crazy, its real

**Comment by LoannMKW** [comment]
its really something with the app

**Comment by GabubuAvailable** [comment]
Just for checking, can I have a picture of your SD card from you both?

**Comment by LoannMKW** [comment]
Here is the SD Card of my friend :
![image](https://github.com/OpenShopChannel/outdated-apps/assets/151388753/0b505d73-df37-46b6-94ac-46a9b4526c95)

**Comment by LoannMKW** [comment]
SD Card of my 2nd friend :
![image](https://github.com/OpenShopChannel/outdated-apps/assets/151388753/572275dd-c755-4d38-94b0-22ef0c24da5b)

**Comment by LoannMKW** [comment]
(They told me that they succesfully formated their sd card too*)

**Comment by ghost** [comment]
> SD Card of my 2nd friend : ![image](https://private-user-images.githubusercontent.com/151388753/347951243-572275dd-c755-4d38-94b0-22ef0c24da5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MjM4MDIsIm5iZiI6MTcyMDcyMzUwMiwicGF0aCI6Ii8xNTEzODg3NTMvMzQ3OTUxMjQzLTU3MjI3NWRkLWM3NTUtNGQzOC05NGIwLTIyZWYwYzI0ZGE1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQxODQ1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTVmNTYxZWFlNmYyYWM1ZmI0NzViNmE0OWI4MDAzMjI4MTA3MDhjNWU1MTc1ZGFlMmIyMjdkNmE4NWYyMTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O1wwrW25kez66y8DuvjnAqw1iPcPsz19tts8geqkjUw)

yeah this is mine

**Comment by GabubuAvailable** [comment]
Yeah the one from Marioexpert is not from SanDisk... The adapter is but that doesn't count. Yours is from PNY (a chinese brand mostly). Now since the SD card are formated now, you can perform a test, to see if your SD card have a real capacity or not. For this you can try [ValiDrive](https://www.grc.com/validrive.htm). A simple tool which formats the SD Card then check the true capacity. This is used for checking if your SD card is having a fake capacity or not.

**Comment by GabubuAvailable** [comment]
Before you try ValiDrive make sure you select the correct partition (a.k.a SD card)

**Comment by Artuto** [comment]
I tried the app in Dolphin and it just froze, didn't damage the virtual SD Card, why do you think this app corrupted your SD card?

**Comment by ghost** [comment]
> I tried the app in Dolphin and it just froze, didn't damage the virtual SD Card, why do you think this app corrupted your SD card?

Most of the time dolphin can't do real hardware things

**Comment by LoannMKW** [comment]
> I tried the app in Dolphin and it just froze, didn't damage the virtual SD Card, why do you think this app corrupted your SD card?

Yes it crash, and after it corrupt the SD Card (But i dont work on dolphin)

**Comment by Naim2000** [comment]
Both SD cards look worn out and/or fake. Especially the "sandisk" one. It's an unlabelled microSD card. Of course it's going to die.

**Comment by Artuto** [comment]
I have to agree that your SD card probably is fake and/or borked.

This app has existed since 2013 and we would have heard by now if it did corrupt SD Cards.

Closing this as inconclusive.
