### ISSUE TITLE
Wii Mod Lite

### ISSUE THREAD

**Issue by sctech-tr** [OpenShopChannel/outdated-apps#108]
### Currently Listed Version

v1.7

### URL to new version

https://github.com/modmii/YAWM-ModMii-Edition/releases/download/1.0.1/yawmME.zip

### Version of Updated App

yawmME

### Select listing type

Apps

### More Information

yawmME is far better than Wii Mod Lite. and even though it is listed as deprecated, I think it should be removed (for wiis to not get tortured). also, I know this is an 'outdated version' issue form, but I couldn't find a better place to say it.

**Comment by playerjmr** [comment]
We already tried https://github.com/OpenShopChannel/Apps/issues/23

**Comment by Artuto** [comment]
This was already discussed.
