### ISSUE TITLE
RiiConnect24 Clear Tool Outdated

### ISSUE THREAD

**Issue by Itsamejonah** [OpenShopChannel/outdated-apps#110]
### Currently Listed Version

v1.0.1

### URL to new version

https://www.wiilink24.com/

### Version of Updated App

idk the latest version of wiilink

### Listing type

Apps

### More Info

Riiconect24 is part of wiilink now, thanks.

**Comment by hwalker56** [comment]
please do more research, there are no newer versions.

**Comment by GabubuAvailable** [comment]
Sorry but there is no updated version atm by RC24/WL24. The link you sent is useles...

**Comment by Itsamejonah** [comment]
riiconect24 is part of wiilink know, going to rc24 brings you to
wiilink24.com. Thanks.

**Comment by GabubuAvailable** [comment]
We are talking about the app itself... Wiilink never made update about it.

**Comment by Itsamejonah** [comment]
wiilink now owns riiconect24 🥟🕺🏻

**Comment by playerjmr** [comment]
> ### Version of Updated App
> idk the latest version of wiilink

that’s because there IS NO WIILINK CLEAR TOOL.
wiilink never bothered to rebrand that tool because it would sometimes cause bricks on Wiis. The clear tool should be avoided at all costs.

**Comment by Itsamejonah** [comment]
Ok, thanks for the clarification.
