### ISSUE TITLE
system-channel-restorer

### ISSUE THREAD

**Issue by xflak** [OpenShopChannel/outdated-apps#111]
### Currently Listed Version

1.0

### URL to new version

https://github.com/Naim2000/system-channel-restorer/releases/tag/1.1

### Version of Updated App

1.1

### Select listing type

Apps

### More Information

No.

**Comment by Artuto** [comment]
We are serving 1.1, but the author forgot to update the version in meta.xml.

**Comment by Naim2000** [comment]
> We are serving 1.1, but the author forgot to update the version in meta.xml.

Lol oops. Maybe I should make a meta.xml template
