### ISSUE TITLE
Configurable USB Loader

### ISSUE THREAD

**Issue by leahanderson1** [OpenShopChannel/outdated-apps#112]
### Currently Listed Version

70 Mod r78.12

### URL to new version

https://github.com/nitraiolo/CfgUSBLoader

### Version of Updated App

70 Mod r78.13

### Select listing type

Apps

### More Information

No.

**Comment by GabubuAvailable** [comment]
Thank you @OtterCodes101!
I've updated it now. In a few moments it will be updated to the latest version!
