### ISSUE TITLE
WiiFlow WFL

### ISSUE THREAD

**Issue by mlm-games** [OpenShopChannel/outdated-apps#114]
### Currently Listed Version

5.5.4

### URL to new version

https://github.com/Fledge68/WiiFlow_Lite/releases/

### Version of Updated App

5.5.4-1

### Select listing type

Apps

### More Information

No.

**Comment by Artuto** [comment]
Version is 5.5.4-1 but author didn't update the meta.xml

![image](https://github.com/user-attachments/assets/7437a9ac-6e28-40d4-9ab0-3b3029069ea2)

![image](https://github.com/user-attachments/assets/278bdb2c-9c8f-4b3f-bb3b-862c742b9a2f)
