### ISSUE TITLE
WiiSXRX

### ISSUE THREAD

**Issue by chasio2221** [OpenShopChannel/outdated-apps#115]
### Currently Listed Version

3.3 Beta

### URL to new version

https://gbatemp.net/threads/wiisx-rx-a-new-fork.570252/post-9137668

### Version of Updated App

4.0 Preview

### Select listing type

Apps

### More Information

This runs much better then 3.3

**Comment by Artuto** [comment]
We have the latest, the author must upload the updated version to their GitHub repo.
![image](https://github.com/user-attachments/assets/8748e412-740c-4dff-9e77-bcfbbc3cefa6)
