### ISSUE TITLE
WiiLink Mail Patcher

### ISSUE THREAD

**Issue by Zw9876** [OpenShopChannel/outdated-apps#116]
### Currently Listed Version

2.0.1

### URL to new version

https://github.com/WiiLink24/WiiLink24-Patcher/releases

### Version of Updated App

2.0.4

### Select listing type

Apps

### More Information

No.

**Comment by Artuto** [comment]
That is a PC application, not a Wii app
![image](https://github.com/user-attachments/assets/ab3acb94-f22a-4540-a8ac-fdfe6b67d382)

**Comment by Zw9876** [comment]
I am sorry. I thought that it was the mail patcher.
