### ISSUE TITLE
WiiWare 43DB patcher

### ISSUE THREAD

**Issue by DraconicNEO** [OpenShopChannel/outdated-apps#12]
latest current version is 0.2
https://github.com/DarkMatterCore/ww-43db-patcher/releases/latest

**Comment by larsenv** [comment]
Updated. @dhtdht020, was there a reason why it was never updated?

**Comment by DraconicNEO** [comment]
> 
> 
> Updated. @dhtdht020, was there a reason why it was never updated?

Not sure, Just know that I was getting an error using it with themes then I realized it was outdated.
