### ISSUE TITLE
WiiMC-SS

### ISSUE THREAD

**Issue by nikku4211** [OpenShopChannel/outdated-apps#19]
### Currently Listed Version

v1.3.8

### URL to new version

https://gbatemp.net/threads/wiimc-ss-gamecube-controller-support-and-more.469452/

### Version of Updated App

v2.0.0

### Select listing type

Apps

### More Information

This new version of WiiMC-SS has a blue logo in the Homebrew Channel.

**Comment by larsenv** [comment]
Thanks for letting us know. Updated it. Looks like that version was released in January, I'm embarrassed about some of our homebrew being outdated without our knowledge.

**Comment by larsenv** [comment]
Off-topic, but for the record, I think keeping up to date with WiiDatabase is the way to go, I know the guy who runs it and he subscribes to a lot of RSS feeds to get information about updates.

By the way he told me he's "jealous" of Open Shop Channel lol.

**Comment by nikku4211** [comment]
> Off-topic, but for the record, I think keeping up to date with WiiDatabase is the way to go, I know the guy who runs it and he subscribes to a lot of RSS feeds to get information about updates.

Good idea, but isn't WiiDatabase in German? You'd have to constantly contact him to get a translation every time, right?

**Comment by larsenv** [comment]
Lmao no. Despite it being German, I can still understand the title.

By the way, the owner speaks English very well. Thankfully people in Germany and the Netherlands learn English in school...

**Comment by nikku4211** [comment]
> Lmao no. Despite it being German, I can still understand the title.

So you only need to know the titles?

> By the way, the owner speaks English very well. Thankfully people in Germany and the Netherlands learn English in school...

Yeah, I know, hence why I talked about contacting the owner.

**Comment by larsenv** [comment]
Yeah, I'm subscribed to his RSS feed. And I have his Telegram lol

**Comment by nikku4211** [comment]
> Yeah, I'm subscribed to his RSS feed. And I have his Telegram lol

Oh, okay, because I don't know what being subscribed to WiiDatabase's RSS is like.

**Comment by larsenv** [comment]
here

https://wiidatabase.de/feed/
