### ISSUE TITLE
Update FCEUX TX to 1.1.2

### ISSUE THREAD

**Issue by saulfabregwiivc** [OpenShopChannel/outdated-apps#20]
### Currently Listed Version

1.1.1

### URL to new version

https://gbatemp.net/threads/fceugx-1up.558023/

### Version of Updated App

1.1.2

### Select listing type

Apps

### More Information

In the attachments of the post # 1 of the thread here's the updated version of FCEUX TX (1.1.2).
This version was released on September 1, 2021.

**Comment by larsenv** [comment]
Updated, sorry for the delay.
