### ISSUE TITLE
Update Snes9x TX to 1.0.8

### ISSUE THREAD

**Issue by saulfabregwiivc** [OpenShopChannel/outdated-apps#21]
### Currently Listed Version

1.0.7

### URL to new version

https://gbatemp.net/threads/snes9xgx-mushroom.558500/

### Version of Updated App

1.0.8

### Select listing type

Apps

### More Information

In the attachments of the post # 1 of the thread here's the updated version of Snes9x TX (1.0.8).
This version was released on September 1, 2021.
Since there's also an US theme, then preferably take the Snes9x-TX-1.0.8-Wii.zip archive.

**Comment by larsenv** [comment]
Updated, sorry for the delay.
