### ISSUE TITLE
Update WiiMednafen to 0.3-SNAPSHOT

### ISSUE THREAD

**Issue by saulfabregwiivc** [OpenShopChannel/outdated-apps#22]
### Currently Listed Version

0.2-pre

### URL to new version

https://github.com/raz0red/wii-mednafen/actions/runs/1419210870

### Version of Updated App

0.3-SNAPSHOT

### Select listing type

Apps

### More Information

There's some artifacts with the latest builds of WiiMednafen 0.3-SNAPSHOT.
In this page http://github.com/raz0red/wii-mednafen/actions here you can find some latest builds of WiiMednafen since last release (0.2-pre), these builds are of new 0.3-SNAPSHOT, with new improvements.
EDIT: If downloading from GitHub, download the "dist" file, then open the dist.zip file of WiiMednafen, and inside it you will find the updated WiiMednafen with all the settings and boot.dol/icon.png/meta.xml.
EDIT 2: This version was released in November 3, 2021.

In this another page you can get the WiiMednafen 0.3 directly: https://gbatemp.net/download/wiimednafen.37238/

**Comment by saulfabregwiivc** [comment]
First message updated with release date of the latest WiiMednafen

**Comment by saulfabregwiivc** [comment]
Any chance for updating on OSC Wii the emulator WiiMednafen to 0.3-SNAPSHOT? The downloads of the official release can be found in the post 1 ( https://github.com/OpenShopChannel/outdated-apps/issues/22#issue-1057525972 )

**Comment by larsenv** [comment]
I'd rather wait until a stable release rather than updating the app with every commit.

**Comment by saulfabregwiivc** [comment]
Well, that's OK, but the author (raz0red) had stopped a bit development of both WiiMednafen and WiiColEm, its latest change of WiiMednafen was improving PC-FX and SEGA Mega Drive/Genesis emulation, and also fix some issues with that (all of these finished made in 2020).

EDIT: edited, contained incorrect info
