### ISSUE TITLE
Update WiiColEm to 0.4-SNAPSHOT

### ISSUE THREAD

**Issue by saulfabregwiivc** [OpenShopChannel/outdated-apps#23]
### Currently Listed Version

0.3

### URL to new version

https://github.com/raz0red/wiicolem/actions/runs/1346399932

### Version of Updated App

0.4-SNAPSHOT

### Select listing type

Apps

### More Information

There's some artifacts with the latest builds of WiiColEm 0.4-SNAPSHOT.
In this page http://github.com/raz0red/wiicolem/actions here you can find some latest builds of WiiColEm since last release (0.3), these builds are of new 0.4-SNAPSHOT, with new improvements.
EDIT: If downloading from GitHub, download the "dist" file, then open the dist.zip file of WiiColEm, and inside it you will find the updated WiiColEm with all the settings and boot.dol/icon.png/meta.xml.
EDIT 2: This version was released in October 15, 2021.

In this another page you can get the WiiColEm 0.4 directly: https://gbatemp.net/download/wiicolem.37283/

**Comment by saulfabregwiivc** [comment]
First message updated with release date of the latest WiiColEm

**Comment by saulfabregwiivc** [comment]
Any chance for updating on OSC Wii the emulator WiiColEm to 0.4-SNAPSHOT? The downloads of the official release can be found in the post 1 ( https://github.com/OpenShopChannel/outdated-apps/issues/23#issue-1057526705 )

**Comment by larsenv** [comment]
I'd rather wait until a stable release rather than updating the app with every commit.

**Comment by saulfabregwiivc** [comment]
Well, that's OK, but the author (raz0red) had stopped a bit development of both WiiMednafen and WiiColEm, its latest change of WiiColEm was adding multiple default screen sizes and updating to latest wii-emucommon (done in January 2020).

EDIT: edited, contained incorrect info
