### ISSUE TITLE
Update Genesis Plus GX to 1.7.5RC1 (r24-10-2021)

### ISSUE THREAD

**Issue by saulfabregwiivc** [OpenShopChannel/outdated-apps#24]
### Currently Listed Version

1.7.5

### URL to new version

https://github.com/ekeeke/Genesis-Plus-GX/tree/master/builds

### Version of Updated App

1.7.5RC1 (r24-10-2021)

### Select listing type

Apps

### More Information

In the link mentioned (http://github.com/ekeeke/Genesis-Plus-GX/tree/master/builds) you can only find the most recent dol files of the latest build of Genesis Plus GX, **genplus_cube.dol** is for GameCube, **genplus_wii.dol** is for Wii.
Latest version was 1.7.5RC1 (r24-10-2021), which was released in October 24, 2021.
Grab the **genplus_wii.dol** for download the Wii version, then replace the old **boot.dol** fileof the archive with this new version. (edited)

In your actual zip file in Open Shop Channel, you will need to edit manually the meta.xml for change the version and release date.
The meta.xml should be like this for the latest version:
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`
`<app version="1">`
`  <name>Genesis Plus GX</name>`
`  <coder>Eke-Eke</coder>`
`  <version>1.7.5-RC1 r24-10-2021</version>`
`  <release_date>24/10/2021</release_date>`
`  <short_description>Sega 8-bit/16-bit emulator</short_description>`
`  <long_description>`
`This is a Sega / Mega CD, Mega Drive / Genesis, Master System, Game Gear &amp; SG-1000 emulator based on the initial work of Charles MacDonald. The original code has been highly modified to improve emulation accuracy as well as adding many extra features, in order to provide 100% game compatibility with emulated systems. For any questions, make sure to read the user manual first and visit official homepage at http://github.com/ekeeke/Genesis-Plus-GX`
`  </long_description>`
`  <ahb_access/>`
`</app>`

**Comment by larsenv** [comment]
Updated, sorry for the delay.

**Comment by saulfabregwiivc** [comment]
@larsenv 

Excuse me, but the release date of Genesis Plus GX 1.7.5-RC1 r24-10-2021 was accidentally set to November 27, 2021.
The version was released in October 24, 2021, please correct it :P

**Comment by saulfabregwiivc** [comment]
Since on OSC Discord i've noticed a issue with OSC Wii (Homebrew Browser) with Genesis Plus GX, i've noticed that the cause of the crashes is because of an "incorrect" meta.xml file.

Please update it with this:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<app version="1">
<name>Genesis Plus GX</name>
<coder>Eke-Eke</coder>
<version>1.7.5-RC1 r24-10-2021</version>
<release_date>20211024</release_date>
<short_description>Sega 8-bit/16-bit emulator</short_description>
<long_description>This is a Sega / Mega CD, Mega Drive / Genesis, Master System, Game Gear and SG-1000 emulator based on the initial work of Charles MacDonald.</long_description>
<ahb_access/>
</app>
```
EDIT: I've attached a proper meta.xml for update Genesis Plus GX and (hopefully) fix the issue with OSC Wii.
[Genesis Plus GX proper meta.xml (FIX 3).zip](https://github.com/OpenShopChannel/outdated-apps/files/7643554/Genesis.Plus.GX.proper.meta.xml.FIX.3.zip)

EDIT 2: Since meta.xml is a bit malformed (and had a too long description), i updated with a fixed one, and the description is shortened.

Hope this can be fixed soon.

**Comment by dhtdht020** [comment]
> Since on OSC Discord i've noticed a issue with OSC Wii (Homebrew Browser) with Genesis Plus GX, i've noticed that the cause of the crashes is because of an "incorrect" meta.xml file.
> 
> Please update it with this:
> 
> ```
> <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
> <app version="1">
> <name>Genesis Plus GX</name>
> <coder>Eke-Eke</coder>
> <version>1.7.5-RC1 r24-10-2021</version>
> <release_date>20211024</release_date>
> <short_description>Sega 8-bit/16-bit emulator</short_description>
> <long_description>This is a Sega / Mega CD, Mega Drive / Genesis, Master System, Game Gear and SG-1000 emulator based on the initial work of Charles MacDonald.</long_description>
> <ahb_access/>
> </app>
> ```
> 
> EDIT: I've attached a proper meta.xml for update Genesis Plus GX and (hopefully) fix the issue with OSC Wii. [Genesis Plus GX proper meta.xml (FIX 3).zip](https://github.com/OpenShopChannel/outdated-apps/files/7643554/Genesis.Plus.GX.proper.meta.xml.FIX.3.zip)
> 
> EDIT 2: Since meta.xml is a bit malformed (and had a too long description), i updated with a fixed one, and the description is shortened.
> 
> Hope this can be fixed soon.

Fixed the description length.
