### ISSUE TITLE
SaveGame Manager GX

### ISSUE THREAD

**Issue by sfreyux** [OpenShopChannel/outdated-apps#25]
### Currently Listed Version

rev76

### URL to new version

https://sourceforge.net/projects/savegame-manager-gx/

### Version of Updated App

rev127

### Select listing type

Apps

**Comment by larsenv** [comment]
It's not outdated, I think the meta.xml shows the wrong version.

We use the beta version, which despite being a beta, is more stable and better than the stable version.
