### ISSUE TITLE
WiiBrowser

### ISSUE THREAD

**Issue by abso1utezer0** [OpenShopChannel/outdated-apps#26]
### Currently Listed Version

rev132

### URL to new version

https://web.archive.org/web/20160420030440/https://code.google.com/p/wiibrowser/downloads/detail?name=R120.dol

### Version of Updated App

rev120

### Select listing type

Apps

### More Information

The latest version of the app is not functional due to a bug. The second latest version should be used so the app can function correctly again.

**Comment by larsenv** [comment]
Nice catch! I first-handedly noticed that WiiBrowser wasn't working on the latest version, this must be why. Changed.

**Comment by larsenv** [comment]
@abso1utezer0 hey, can you please explain why this version of WiiBrowser works? I tried the latest version and the one you submitted, but neither of them seem to load anything, not even Google.

I tried to reach out to you on Discord for this, but I didn't get a response.

**Comment by TheTechRobo** [comment]
If you look at Michael MJD's video, the new version just shows a blank dialog box with "WiiBrowser" at the top. The older version supposedly doesn't have this bug although I haven't tested it.

**Comment by abso1utezer0** [comment]
> @abso1utezer0 hey, can you please explain why this version of WiiBrowser works? I tried the latest version and the one you submitted, but neither of them seem to load anything, not even Google.
> 
> I tried to reach out to you on Discord for this, but I didn't get a response.

That's odd. I tested it on a real Wii and it seemed to work perfectly (besides the horribly slow and outdated view of websites, which is expected). Perhaps your network connection wasn't going through?

**Comment by Andrew-J-Larson** [comment]
I think the issue here is that it's not working properly on the vWii. As far as my testing has gone (almost always crashes with DSI error)

**Comment by TheTechRobo** [comment]
There's a different problem with the real Wii. See Michael MJD's video on browsing the Internet on the Wii in 2021.

**Comment by Andrew-J-Larson** [comment]
I did notice something, if r132 has access to files created from previous versions of the browser, it does load.

> > @abso1utezer0 hey, can you please explain why this version of WiiBrowser works? I tried the latest version and the one you submitted, but neither of them seem to load anything, not even Google.
> > I tried to reach out to you on Discord for this, but I didn't get a response.
> 
> That's odd. I tested it on a real Wii and it seemed to work perfectly (besides the horribly slow and outdated view of websites, which is expected). Perhaps your network connection wasn't going through?

I wonder if the reason why abso1utezer0 was able to load pages is he has something cached/downloaded in his files, that can't be found anymore (maybe something the WiiBrowser would point to, to download additional files outside of the normal updates)

**Comment by Andrew-J-Larson** [comment]
@abso1utezer0 could you zip up your instance of the browser and send it here for testing?
