### ISSUE TITLE
mGBA

### ISSUE THREAD

**Issue by CrafterPika** [OpenShopChannel/outdated-apps#29]
### Currently Listed Version

0.9.2

### URL to new version

https://mgba.io/2021/12/17/mgba-0.9.3/

### Version of Updated App

0.9.3

### Select listing type

Apps

### More Information

No.

**Comment by saulfabregwiivc** [comment]
That link you put isn't a download link for mGBA Wii 0.9.3.
A direct download link for mGBA Wii 0.9.3: https://github.com/mgba-emu/mgba/releases/download/0.9.3/mGBA-0.9.3-wii.7z

**Comment by larsenv** [comment]
Fixed.
