### ISSUE TITLE
mGBA

### ISSUE THREAD

**Issue by LiveLM** [OpenShopChannel/outdated-apps#31]
### Currently Listed Version

0.9.2

### URL to new version

https://github.com/mgba-emu/mgba/releases/tag/0.9.3

### Version of Updated App

0.9.3

### Select listing type

Apps

### More Information

The current mGBA .zip on the shop is the 0.9.2 version, with the 0.9.3 version inside it for some reason???
No idea what happened there
![image](https://user-images.githubusercontent.com/34987841/157109263-e06c7a5c-db8b-43b7-9d2d-f434809e4cb2.png)

**Comment by dhtdht020** [comment]
Looks like an update was stopped midway through, problem solved.
