### ISSUE TITLE
Priiloader

### ISSUE THREAD

**Issue by Gxinz** [OpenShopChannel/outdated-apps#32]
### Currently Listed Version

0.9.1

### URL to new version

https://github.com/DacoTaco/priiloader/releases/tag/0.10.0-beta1

### Version of Updated App

0.10.0-b1

### Select listing type

Apps

### More Information

No.

**Comment by TheTechRobo** [comment]
That's a beta, though.

Does the OSC accept betas?

**Comment by Gxinz** [comment]
maybe, we'll see :D

**Comment by dhtdht020** [comment]
Hello, I appreciate the report, but we only update to stable releases.
