### ISSUE TITLE
Wii64 | glN64 GFX

### ISSUE THREAD

**Issue by saulfabregwiivc** [OpenShopChannel/outdated-apps#33]
### Currently Listed Version

Beta 1.3

### URL to new version

https://github.com/saulfabregwiivc/Wii64/releases/tag/wii641.3.wiiflow.5

### Version of Updated App

Beta 1.3 WF MOD Beta5

### Select listing type

Apps

### More Information

My friend @xflak (author of ModMii) have requested time ago to add my WiiFlow Compatibility MOD of Wii64 1.3 to the Open Shop Channel Wii (i think since XFlak told me?).
But a few days ago i've updated again my [WiiFlow MOD](https://github.com/saulfabregwiivc/Wii64/releases/tag/wii641.3.wiiflow.5), so please consider updating this.

If the version i'm saying is too long, then leave the version to "Beta 1.3" (since it's an unofficial mod) and only update the description for say that the version of my WiiFlow MOD is Beta5.

EDIT: Forgot to say, please use the dols labeled "WiiVC" since these have Wii U GamePad support and CPU clock divider (vWii overclock support).

**Important:** I've also updated my **RiceVideoLinux.ini** file for [add fixes for some missing games](https://github.com/saulfabregwiivc/Wii64/commit/7194b4f24b581c1d4f98cd59d2f6090da5861297), so please also update the RiceVideoLinux.ini file (inside **root:/wii64** folder, NOT from root:/apps/wii64 folder) with this one here:
https://raw.githubusercontent.com/saulfabregwiivc/Wii64/wii64-wiiflow/release/wii64/RiceVideoLinux.ini

**Comment by dhtdht020** [comment]
Sorry for the wait, was busy in the past few days.
Updated app as specified.
