### ISSUE TITLE
Snes9x RX

### ISSUE THREAD

**Issue by saulfabregwiivc** [OpenShopChannel/outdated-apps#34]
### Currently Listed Version

4.9.0

### URL to new version

https://github.com/niuus/Snes9xRX/releases/tag/5.0.0

### Version of Updated App

5.0.0

### Select listing type

Apps

### More Information

You must grab the file called "[Snes9xRX-5.0.0.zip](https://github.com/niuus/Snes9xRX/releases/download/5.0.0/Snes9xRX-5.0.0.zip)" on the Releases.
There are other archives in the releases tab for this new version 5.0.0 but that's for GameCube and Wii with turbo disabled.

**Comment by dhtdht020** [comment]
Sorry for the very long wait, updated.
