### ISSUE TITLE
ww-43db-patcher contains second outdated copy in zip

### ISSUE THREAD

**Issue by Brycey92** [OpenShopChannel/outdated-apps#36]
### Currently Listed Version

0.2

### URL to new version

https://oscwii.org/library/app/ww-43db-patcher

### Version of Updated App

0.2

### Select listing type

Apps

### More Information

The current zip file available for download contains BOTH the 0.1 version in the root of the zip, and the 0.2 version in the proper place in the apps folder.

**Comment by dhtdht020** [comment]
Sorry for the wait, fixed.
