### ISSUE TITLE
WoxelCraft

### ISSUE THREAD

**Issue by charlieduzstuf** [OpenShopChannel/outdated-apps#39]
### Currently Listed Version

0.0.7

### URL to new version

https://github.com/kperdlich/wiicraft/releases

### Version of Updated App

v1.0 

### Select listing type

Apps

### More Information

Its more of a woxel craft remaster than an update but it is the same code made by the same guy, just with a different name

**Comment by Artuto** [comment]
It seems the remaster is no longer distributed as a Homebrew Channel app, but as a Wiiloader .dol file, which is not supported by how our repository works (it's also missing the HBC meta.xml)
