### ISSUE TITLE
Wii7800

### ISSUE THREAD

**Issue by Brycey92** [OpenShopChannel/outdated-apps#43]
### Currently Listed Version

0.5

### URL to new version

https://github.com/raz0red/wii7800/releases/tag/0.5

### Version of Updated App

0.5

### Select listing type

Apps

### More Information

Everything in the app's folder is the same as oscwii's current zip, but the folder should be named "wii7800" instead of "WII7800", and the wii7800 folder at the root of the SD card should be added to oscwii's zip for the app to function.

**Comment by dhtdht020** [comment]
Hello, sorry for the delay and the trouble, been busy for the past few days.
I've corrected the contents of the zip file, not sure what happened there.
