### ISSUE TITLE
Covid 19 Apocalapse

### ISSUE THREAD

**Issue by StickyDigit** [OpenShopChannel/outdated-apps#44]
### Currently Listed Version

1.0

### URL to new version

https://github.com/softwaregremlin/Covid-19-Apocalypse/releases

### Version of Updated App

1.0-proper?

### Select listing type

Apps

### More Information

On OSC there's no zip, and the boot.dol version predates the version on the authors site, though the other files are the same, so both are at v.1.0 in the xml. The OSC version cannot quit with the home button after the game. In the newer version, reload is with 'A' rather than pointing to the bottom of the screen.

**Comment by dhtdht020** [comment]
Thank you, updated.
