### ISSUE TITLE
WIISXRX

### ISSUE THREAD

**Issue by lankv2** [OpenShopChannel/outdated-apps#48]
### Currently Listed Version

3.1 Beta

### URL to new version

https://github.com/niuus/WiiSXRX/releases/tag/v3.2

### Version of Updated App

v3.2

### Select listing type

Apps

### More Information

WiiSXRX-FS is recommended for use on the Wii but does not support red book audio (CDDA). So choose 
WiiSXRX-3.2-FS.zip.

**Comment by larsenv** [comment]
Updated.
