### ISSUE TITLE
Settings Editor GUI

### ISSUE THREAD

**Issue by yanisdreemurr** [OpenShopChannel/outdated-apps#5]
There was a new update of "Settings Editor GUI"

The link is : http://www.hacksden.com/showthread.php/3142-Settings-Editor-GUI

**Comment by dhtdht020** [comment]
Hello, sorry for keeping that waiting.
The developer did not update the meta.xml file (which says it's an older version), which is problematic because of the way the osc is managed.
For that reason, this request cannot be processed.
There's not much we can do about this.
