### ISSUE TITLE
SaveGame Manager GX

### ISSUE THREAD

**Issue by Maidvelia** [OpenShopChannel/outdated-apps#53]
### Currently Listed Version

rev76

### URL to new version

https://sourceforge.net/projects/savegame-manager-gx/

### Version of Updated App

rev127

### Select listing type

Apps

### More Information

HBC_SetUp_R127.zip for Wii
vWii_R127.dol for vWii

**Comment by larsenv** [comment]
This app isn't outdated. The version that we host is a beta version that works better. The meta.xml is outdated. I guess that should be fixed.

**Comment by Maidvelia** [comment]
Apologies. I completely went off what the meta.xml said for this, heh. D:
