### ISSUE TITLE
Nintendont

### ISSUE THREAD

**Issue by danielsahr528** [OpenShopChannel/outdated-apps#54]
### Currently Listed Version

6.492

### URL to new version

https://github.com/FIX94/Nintendont/tree/master/loader

### Version of Updated App

6.499

### Select listing type

Apps

### More Information

The meta.xml has not been updated since 4.431 in 2016, but the loader.dol itself is rebuilt with the latest commits and bug fixes

**Comment by larsenv** [comment]
Updated. Sorry that this took so long. I have write access to this repository now therefore I can more easily check to see what's outdated.
