### ISSUE TITLE
Nintendont

### ISSUE THREAD

**Issue by RetraCarteR** [OpenShopChannel/outdated-apps#55]
### Currently Listed Version

6.492

### URL to new version

https://github.com/FIX94/Nintendont

### Version of Updated App

6.499

### Select listing type

Apps

### More Information

Links to download the boot.dol, meta.xml, and icon.png are provided in the readme on the GitHub page, under "Quick Installation". The meta.xml file incorrectly lists an outdated version number and build date. The app is currently in version 6.499 and was last updated on November 1, 2022.

**Comment by larsenv** [comment]
Updated. Sorry that this took so long. I have write access to this repository now therefore I can more easily check to see what's outdated.
