### ISSUE TITLE
USB Loader GX

### ISSUE THREAD

**Issue by Snare-Hawk** [OpenShopChannel/outdated-apps#58]
### Currently Listed Version

3.0 r1272

### URL to new version

https://github.com/wiidev/usbloadergx/releases/tag/v3.0-r1280

### Version of Updated App

3.0 r1280

### Select listing type

Apps

### More Information

No.

**Comment by dhtdht020** [comment]
hello, this is already up to date, will investigate why the version number shows up incorrectly on website and homebrew browser.
