### ISSUE TITLE
USB Loader GX

### ISSUE THREAD

**Issue by wiidev** [OpenShopChannel/outdated-apps#60]
### Currently Listed Version

3.0 r1280

### URL to new version

https://github.com/wiidev/usbloadergx/releases/tag/v3.0-r1281

### Version of Updated App

3.0 r1281

### Select listing type

Apps

### More Information

`boot_non480pfix.dol (r1272)` and `480p fix info.txt` are no longer required.

**Comment by dhtdht020** [comment]
Thanks for the report, updated.

**Comment by dhtdht020** [comment]
Also removed files which are no longer required.
