### ISSUE TITLE
Nintendont

### ISSUE THREAD

**Issue by Everythintechyt** [OpenShopChannel/outdated-apps#68]
### Currently Listed Version

4.431

### URL to new version

https://github.com/FIX94/Nintendont

### Version of Updated App

6.500

### Select listing type

Apps

### More Information

No.

**Comment by larsenv** [comment]
This is probably the 4th time that someone says Nintendont's falsely out of date and I'm frustrated. The meta.xml's out of date and not the app. I'm gonna edit the meta.xml to prevent people from making this issue once again.
