### ISSUE TITLE
SaveGame Manager GX

### ISSUE THREAD

**Issue by GFlechas** [OpenShopChannel/outdated-apps#69]
### Currently Listed Version

rev76

### URL to new version

https://sourceforge.net/projects/savegame-manager-gx/files/

### Version of Updated App

rev127

### Select listing type

Apps

### More Information

It looks like the updated boot.dol, icon.pn, and meta.xml are in the HBC_SetUp_R127.zip file on the Sourceforge page for the project. I'm new to homebrew so I'm not sure if there's a better location to work off.

**Comment by larsenv** [comment]
This is not outdated. The meta.xml is.

**Comment by ghost** [comment]
> This is not outdated. The meta.xml is.

even the actual homebrew itself says rev 76 if you go to the about page
