### ISSUE TITLE
CavEX

### ISSUE THREAD

**Issue by AetheralMeowstic** [OpenShopChannel/outdated-apps#70]
### Currently Listed Version

Alpha 0.2.1

### URL to new version

N/A

### Version of Updated App

N/A

### Select listing type

Apps

### More Information

The app is dead, as the Github link leads to a 404. Since it's open-source under GPL 2.0 and hence requires you to provide the source code if requested, the fact that the source code doesn't exist anymore means that distributing it is a violation of GPL 2.0

**Comment by dhtdht020** [comment]
Looking into contacting the author for a stance on this.

**Comment by dhtdht020** [comment]
Thank you for submitting your concern, I have investigated this further and the licensing seems to be a non-issue. The developer privated the repo on GitHub a while after publishing the last official distribution which matches OSC's 1:1.

Additionally, the app isn't dead, it was dropped last month and is still officially distributed.

**Comment by xtreme8000** [comment]
Hi, the repo was always private. The link is there for when the repo will be set public soonish. It is currently missing foss assets and build instructions.
> Looking into contacting the author for a stance on this.

Please feel free to ping me on future issues. You can also reach me on the OpenShopChannel discord, I'm there.

> Since it's open-source under GPL 2.0

The code is GPLv3.

**Comment by dhtdht020** [comment]
> Hi, the repo was always private. The link is there for when the repo will be set public soonish. It is currently missing foss assets and build instructions.
> > Looking into contacting the author for a stance on this.
> 
> Please feel free to ping me on future issues. You can also reach me on the OpenShopChannel discord, I'm there.
> 
> > Since it's open-source under GPL 2.0
> 
> The code is GPLv3.

Thank you for the clarification!
