### ISSUE TITLE
ResidualVM

### ISSUE THREAD

**Issue by Fancy2209** [OpenShopChannel/outdated-apps#74]
### Currently Listed Version

0.2

### URL to new version

https://oscwii.org/library/app/scummvm

### Version of Updated App

2.7.0

### Select listing type

Apps

### More Information

ResidualVM was Merged into ScummVM a long time ago as far as I am aware, if a engine isn't avaliable on the stable release of SCVM it probably is on the nightlies.

**Comment by larsenv** [comment]
I believe this is removed.
