### ISSUE TITLE
bluemsx-wii

### ISSUE THREAD

**Issue by lankv2** [OpenShopChannel/outdated-apps#76]
### Currently Listed Version

1.0.3

### URL to new version

https://github.com/Wiimpathy/bluemsx-wii/releases/tag/0.3B

### Version of Updated App

1.0.3b

### Select listing type

Apps

### More Information

1.0.3b has the ability to output 480p and the current one does not. that seems to be the only difference but a welcome one.

**Comment by larsenv** [comment]
Done. Sorry for the long delay.
