### ISSUE TITLE
UTag

### ISSUE THREAD

**Issue by Andrew-J-Larson** [OpenShopChannel/outdated-apps#79]
### Currently Listed Version

N/A

### URL to new version

https://github.com/RiiConnect24/UTag/releases/

### Version of Updated App

N/A

### Select listing type

Apps

### More Information

Less of an outdated app thing, and more of an issue of needing to include the old version of UTag that still works on Tiramisu, since all new versions are only built for the newer Aroma environment.

So that there would be two UTag packages, with their environment requirements.

**Comment by larsenv** [comment]
UTag's a Wii U app, we can't put it on here.

**Comment by Andrew-J-Larson** [comment]
Whoops, my bad, must of done this meaning to submit to https://apps.fortheusers.org/wiiu
