### ISSUE TITLE
SaveGame Manager GX

### ISSUE THREAD

**Issue by qwertychouskie** [OpenShopChannel/outdated-apps#81]
### Currently Listed Version

rev76

### URL to new version

https://sourceforge.net/projects/savegame-manager-gx/files/HBC_SetUp_R127.zip/download

### Version of Updated App

R127

### Select listing type

Apps

### More Information

No.

**Comment by TheTechRobo** [comment]
It's not outdated, the meta.xml is outdated.

**Comment by qwertychouskie** [comment]
OK so it turns out SaveGame Manager GX Beta R76 is newer than SaveGame Manager GX R127.  Apparently Beta R76 is a re-write.  That being said, Beta R76 had issues for me that normal R127 didn't.

Ideally, there would be listings for both the normal and Beta versions.

**Comment by larsenv** [comment]
In my experience Beta R76 works nicer than the regular version in many ways. The other version crashes all the time. I have modified the xml file because multiple people have reported this issue.
