### ISSUE TITLE
Priiloader Installer

### ISSUE THREAD

**Issue by drewbyhk** [OpenShopChannel/outdated-apps#82]
### Currently Listed Version

0.9.1

### URL to new version

https://github.com/DacoTaco/priiloader/releases/tag/0.10.0-beta2

### Version of Updated App

0.10.0-beta2

### Select listing type

Apps

### More Information

This is a beta build, so I'm not sure if OSC wants to publish this or not.

If not, the current non-beta build is still 0.9.1.

**Comment by dhtdht020** [comment]
Yes, thanks for the report.
We don't want to publish the beta version of Priiloader.
