### ISSUE TITLE
d2x cIOS installer

### ISSUE THREAD

**Issue by weirdal3333** [OpenShopChannel/outdated-apps#83]
### Currently Listed Version

3.1

### URL to new version

https://github.com/davebaol/d2x-cios/releases/tag/d2x-v11-beta1-FM050

### Version of Updated App

I guess 3.2, it could be v11.1.050

### Select listing type

Apps

### More Information

It's basically the same as the listed version, but it has fakemote support.

**Comment by GabubuAvailable** [comment]
What you sent is meant to be used by ModMii, which is a Windows software, and not used by the official "d2x cIOS installer" app.
