### ISSUE TITLE
mGBA

### ISSUE THREAD

**Issue by RetroFan90** [OpenShopChannel/outdated-apps#84]
### Currently Listed Version

0.10.2

### URL to new version

https://s3.amazonaws.com/mgba/mGBA-build-latest-wii.7z

### Version of Updated App

0.11-8209-5c2a55884

### Select listing type

Apps

### More Information

use dev build instead of stable builds as it adds more options (in most cases)
Keep Up The Good Work :)
[CHANGES.md](https://github.com/OpenShopChannel/outdated-apps/files/12385099/CHANGES.md)

**Comment by dhtdht020** [comment]
Thanks for the report, but our policy is to avoid updating to dev builds unless specifically requested by the author or there is a technical reason to do so.
