### ISSUE TITLE
Genesis Plus GX

### ISSUE THREAD

**Issue by RetroFan90** [OpenShopChannel/outdated-apps#85]
### Currently Listed Version

1.7.5-RC1 r24-10-2021

### URL to new version

https://github.com/ekeeke/Genesis-Plus-GX/raw/master/builds/genplus_wii.dol

### Version of Updated App

1.7.6 06-24-2023

### Select listing type

Apps

### More Information

No.

**Comment by dhtdht020** [comment]
Updated to latest dol. The change won't be reflected in the version field because the author is not providing an updated meta.xml.
