### ISSUE TITLE
WiiSXR

### ISSUE THREAD

**Issue by RetroFan90** [OpenShopChannel/outdated-apps#87]
### Currently Listed Version

Beta 2.3 f0fabad

### URL to new version

https://github.com/xjsxjs197/WiiSXRX_2022/releases/download/WiiStation_Ver2.4/WiiStation_Ver2.4.zip

### Version of Updated App

2.4

### Select listing type

Apps

### More Information

No.

**Comment by dhtdht020** [comment]
Unsure about updating to that since it's a different fork from the ones currently on the Open Shop Channel. Will consider adding as a seperate application.

**Comment by Artuto** [comment]
Closed by [86748c9dacbf057dc7c1aa31bf09618eb7ff862a](https://github.com/OpenShopChannel/Apps/commit/86748c9dacbf057dc7c1aa31bf09618eb7ff862a)
