### ISSUE TITLE
Priiloader

### ISSUE THREAD

**Issue by KCRTR3** [OpenShopChannel/outdated-apps#92]
### Currently Listed Version

0.9.1

### URL to new version

https://github.com/DacoTaco/priiloader/releases/download/0.10.0-RC3/Priiloader_v0_10RC3.zip

### Version of Updated App

0.10.0 RC3 (beta2 is unstable)

### Select listing type

Apps

### More Information

vWii support is added in 0.10.0 RC3

**Comment by GabubuAvailable** [comment]
Note that this is a beta version, not a released one.

**Comment by GabubuAvailable** [comment]
Priiloader finally got an official release to v0.10.0
