### ISSUE TITLE
WiiSX

### ISSUE THREAD

**Issue by emukidid** [OpenShopChannel/outdated-apps#93]
### Currently Listed Version

Beta 3.0

### URL to new version

https://github.com/emukidid/pcsxgc/releases/tag/Beta_4.0

### Version of Updated App

Beta 4.0

### Select listing type

Apps

### More Information

No.

**Comment by dhtdht020** [comment]
Thank you as always for informing us of a new release, the updated version should be available in the next few minutes.

For future reference:
Thanks to our new system, most app updates are now obtained automatically according to their manifest, and so is [WiiSX](https://github.com/OpenShopChannel/Apps/blob/master/contents/wiiSX.oscmeta).

When an update is detected by the system, it is submitted for moderation. This means that updates for this app should usually be automatically available on the OSC around 6-12 hours after being released. [More on that here](https://docs.oscwii.org/repository-manager/information-for-app-developers/faq#how-long-does-it-take-for-an-application-or-update-to-show-up-on-the-repository).

**Comment by emukidid** [comment]
My bad, that's a great system! I just looked at the metadata and realised it was probably automated after I'd opened the issue.
