### ISSUE TITLE
CavEX

### ISSUE THREAD

**Issue by xtreme8000** [OpenShopChannel/outdated-apps#96]
### Currently Listed Version

Alpha 0.2.1

### URL to new version

https://aos.party/download_public/cavex_a003.zip

### Version of Updated App

Alpha 0.3.0

### Select listing type

Apps

### More Information

Can an update keep existing worlds? It might not be the best idea to override existing worlds which players spent a lot of time on.

**Comment by Artuto** [comment]
Already updated.
