### ISSUE TITLE
Sonic CD

### ISSUE THREAD

**Issue by ultra0000** [OpenShopChannel/outdated-apps#99]
### Currently Listed Version

Wii 2.0.1 (v1.3.0)

### URL to new version

https://github.com/ultra0000/Sonic-CD-11-Decompilation/releases/latest

### Version of Updated App

Wii v3.0.1

### Select listing type

Apps

### More Information

The port now supports the Classic controller, the GameCube controller, and using a Nunchuck and a Wii Remote.

**Comment by Artuto** [comment]
The app folder has been renamed to `RSDKv3`?

**Comment by ultra0000** [comment]
Yes, is that a problem?

**Comment by Artuto** [comment]
Nope, just checking.

**Comment by ultra0000** [comment]
Got it.
